### ISSUE TITLE
Unable to edit files from fluidd interface

### ISSUE THREAD

**Issue by shaunmulligan** [dimalo/klipper-web-control-docker#19]
Hi @dimalo thanks for this amazing project!! I have been trying to adapt it for my own needs, but it seems that its not possible to edit the config files (printer.cfg, etc) from the fluidd interface. I always get the below error, which seems to be due to the fact that moonraker writes to a /tmp directory which is on a different filesystem to the config VOLUME you define. Did you have this functionality working or is it something not considered for your use case?

```
22.10.21 15:04:32 (+0200)  fluidd  192.168.86.26 - - [22/Oct/2021:13:04:32 +0000] "POST /server/files/upload HTTP/1.1" 500 2304 "http://whiptail-a20m.local:8010/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
22.10.21 15:04:32 (+0200)  klipper      os.rename(src, real_dst)
22.10.21 15:04:32 (+0200)  klipper  OSError: [Errno 18] Invalid cross-device link: '/tmp/moonraker.upload-176488.mru' -> '/home/klippy/.config/printer.cfg'
22.10.21 15:04:32 (+0200)  klipper  
22.10.21 15:04:32 (+0200)  klipper  During handling of the above exception, another exception occurred:
22.10.21 15:04:32 (+0200)  klipper  
22.10.21 15:04:32 (+0200)  klipper  Traceback (most recent call last):
22.10.21 15:04:32 (+0200)  klipper    File "/home/klippy/moonraker/moonraker/components/file_manager/file_manager.py", line 555, in _process_uploaded_file
22.10.21 15:04:32 (+0200)  klipper      shutil.move(upload_info['tmp_file_path'],
22.10.21 15:04:32 (+0200)  klipper    File "/usr/local/lib/python3.9/shutil.py", line 834, in move
22.10.21 15:04:32 (+0200)  klipper      copy_function(src, real_dst)
22.10.21 15:04:32 (+0200)  klipper    File "/usr/local/lib/python3.9/shutil.py", line 444, in copy2
22.10.21 15:04:32 (+0200)  klipper      copystat(src, dst, follow_symlinks=follow_symlinks)
22.10.21 15:04:32 (+0200)  klipper    File "/usr/local/lib/python3.9/shutil.py", line 383, in copystat
22.10.21 15:04:32 (+0200)  klipper      lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
22.10.21 15:04:32 (+0200)  klipper  PermissionError: [Errno 1] Operation not permitted
```

**Comment by dimalo** [comment]
@shaunmulligan any updates?

**Comment by shaunmulligan** [comment]
Hi @dimalo, sorry unfortunately haven't had much time to experiment with it, but in the short time I tried I couldn't get it to work. I need to try it on a fresh raspberry pi OS install, I am currently trying to do it on OS from [balena.io](https://www.balena.io/) and I'm starting to suspect that perhaps it might be something to do with they way they create volumes. I might need to dig into the moonraker code because I think the fundamental issue is that the config files in a volume is on ext4 and the tmp file that moonraker creates when making an edit is in the container FS which is overlayfs on balenaOS, and i think that triggers the `shutil.py` `OSError: [Errno 18] Invalid cross-device link:` issue. I plan to test it on a regular rpi OS this week to see what is what.

**Comment by dimalo** [comment]
closing stale issue - feel free to reopen if you still struggle... # #
