### ISSUE TITLE
Restarting fluid and mainsail automatically

### ISSUE THREAD

**Issue by ahalekelly** [dimalo/klipper-web-control-docker#20]
I added `restart: unless-stopped` to my docker-compose config for fluidd, this should probably be the default right?

**Comment by Andoramb** [comment]
It depends on what you want to achieve. Multiple options are [valid here](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart):
```
restart: "no"
restart: always
restart: on-failure
restart: unless-stopped
```
