### ISSUE TITLE
Depreciated macro parameters

### ISSUE THREAD

**Issue by Denniso2** [dimalo/klipper-web-control-docker#22]
default_parameter has been depreciated on the latest klipper version.

**Comment by dimalo** [comment]
yep, can you help?

**Comment by Denniso2** [comment]
Sorry but I don't really know how to use github.Changes are simple though as you can see here https://docs.mainsail.xyz/faq/klipper_warnings/deprecated_option

**Comment by s0nify** [comment]
https://github.com/dimalo/klipper-web-control-docker/pull/23

**Comment by Andoramb** [comment]
This should be OK to close based on the above 👍
