### ISSUE TITLE
Klipper crashes on startup on RPI4

### ISSUE THREAD

**Issue by dmonizer** [dimalo/klipper-web-control-docker#25]
Klipper crashes with log similar to:
klipper  Fatal Python error: pyinit_main: can't initialize time
klipper  | Python runtime state: core initialized
klipper  | PermissionError: [Errno 1] Operation not permitted

Solution:
on the host where you run docker compose do:

wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb

and klipper works. Issue can be closed. just thought i'd post it here for others - was quite a headscratcher for me

**Comment by dimalo** [comment]
@dmonizer thanks for pointing out! can you paste your Debian version?
