### ISSUE TITLE
Using klipper.cfg breaks save_config

### ISSUE THREAD

**Issue by ilektron** [dimalo/klipper-web-control-docker#35]
https://github.com/dimalo/klipper-web-control-docker/blob/2162bfe56095912e125acaf71880f3036b025114/klipper/klipper.ini#L4

It looks like using klipper.cfg breaks the SAVE_CONFIG functionality which requires settings to be saved in printer.cfg.

You get the following error with z_offset for [bltouch]

```
23:40:52  $ [save_config]()
23:40:53  !! [SAVE_CONFIG]() section 'bltouch' option 'z_offset' conflicts with included value
```

**Comment by dimalo** [comment]
I have implemented this in #39 and agree it makes sense so one can save properly.
please check if you can...
