### ISSUE TITLE
Include build-essential and gcc-arm-none-eabi to allow making firmwares

### ISSUE THREAD

**Issue by HitLuca** [dimalo/klipper-web-control-docker#38]
The provided image for klipper doesn't have all the necessary packages required to build a new firmware (`build-essential` and `gcc-arm-none-eabi`). Please add them to the docker image thank you!

**Comment by dimalo** [comment]
please have a look at the builder.Dockerfile and use the build_firmware script. I've just removed gcc from the image to a) make it smaller a lot and b) make it more secure

**Comment by HitLuca** [comment]
That clarifies the issue, thanks a lot :)
