### ISSUE TITLE
WebCam with timelapse configuration

### ISSUE THREAD

**Issue by erustyrannus** [dimalo/klipper-web-control-docker#43]
Hello, Thanks for your hard work.

I am unable to add a camera to fluidd, can you please let me know how to do it?

Also, can you tell me if this project is implemented in your build?

https://github.com/mainsail-crew/moonraker-timelapse

**Comment by truong0vanchien** [comment]
You need to add timelapse manually via docker container.
Otherwise, you can add some lines in Dockerfile of Klipper as below:

```
# Install ffmpeg.
RUN apt-get install -y --no-install-recommends ffmpeg

# Install wget.
RUN apt-get install -y wget

# Put timelapse.py to docker container. (timelapse.py is from moonraker timelapse repo)
COPY timelapse.py ${HOME}/moonraker/moonraker/components/timelapse.py
```

**Comment by p0pp3t0n** [comment]
@erustyrannus Did you make it work? My cameras are not being detected by mainsail. I know they are working since i took images using ffmpeg from the container.

**Comment by erustyrannus** [comment]
> @erustyrannus Did you make it work? My cameras are not being detected by mainsail. I know they are working since i took images using ffmpeg from the container.

Hi, no.  I decided to install on a SBC using [Kiauh](https://github.com/th33xitus/kiauh)
