### ISSUE TITLE
Cannot SAVE_CONFIG

### ISSUE THREAD

**Issue by montyx99** [dimalo/klipper-web-control-docker#8]
I had permission issues before with the .config folder. The Moonraker was not able to reach the config folder. I've used the given advice with luck, but I've just figured it out, I cannot save the config online.
Such as I performed a bed mesh leveling and used the SAVE_CONFIG command, and the printer.cfg hasn't been modified. I think that there is an issue with the Klipper container, just I cannot figure it out.

**Comment by dimalo** [comment]
Unfortunately I don't have a better solution for you as in #3 
Please check ownership and permissions on folder and files & run as non-root

**Comment by montyx99** [comment]
> Unfortunately I don't have a better solution for you as in #3
> Please check ownership and permissions on folder and files & run as non-root

Can you help me, what is the user, that the Moonraker uses? I thought that it is the same like the Klipper itself, but it has already permission in case of config folder.

**Comment by dimalo** [comment]
It is the same user (klippy)
No issues for me whatsoever so closing this issue as it seems to be a config issue on your side...
